# Generated by Django 2.0.3 on 2018-03-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=64)),
                ('last_active', models.DateTimeField(verbose_name='date published')),
                ('last_image_url', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
