# Generated by Django 2.0.3 on 2018-03-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='last_active',
            field=models.DateTimeField(verbose_name='last active'),
        ),
    ]
