# Generated by Django 2.0.3 on 2018-03-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20180322_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
