# Generated by Django 2.0.3 on 2018-03-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_camera_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='has_sound',
            field=models.BooleanField(default=False),
        ),
    ]
