# Generated by Django 2.0.3 on 2018-03-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_camera_owner_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotionDetector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=128)),
                ('last_triggered', models.DateTimeField(verbose_name='last triggered')),
                ('url', models.URLField(default='127.0.0.1', max_length=512)),
                ('owner_name', models.CharField(max_length=64)),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='camera',
            name='location',
            field=models.CharField(max_length=128),
        ),
    ]
